### ISSUE TITLE
第一位之后和「@」之前为什么不直接「\\w」？

### ISSUE THREAD

**Issue by archcst** [RubyXing/ThirdWeekCode#1]
https://github.com/RubyXing/ThirdWeekCode/blob/19968f5d4fdfb04c5caedb72e9e4feb0cc4e9fd0/Day3Code/src/RegexTest/Day3homwork.java#L21

第一位之后和「@」之前为什么不直接「\\w」？

**Comment by RubyXing** [comment]
因为第一位之后可以是下划线，数字，字母。[_\\w\\d]，三个任意重复都可以

**Comment by archcst** [comment]
`\w` 包含了下划线、数字、字母

```
\w  匹配任何字类字符，包括下划线。与"[A-Za-z0-9_]"等效。
```
